from agents.data_agent import data_agent
from agents.pm_agent import pm_agent
from agents.marketing_agent import marketing_agent
from agents.risk_agent import risk_agent
from agents.finance_agent import finance_agent
from agents.critic_agent import critic_agent
from tools.sentiment_tool import analyze_sentiment


def get_metric_drop(metric):
    return f"{metric[0]} → {metric[-1]}"


def run_system(metrics, feedback):
    print("===== WAR ROOM START =====")

    # ---------------------------
    # 1. Agent Execution (Traceability)
    # ---------------------------
    print("[STEP] Running Data Agent...")
    data = data_agent(metrics)

    print("[STEP] Running Sentiment Tool...")
    sentiment = analyze_sentiment(feedback)

    print("[STEP] Running Marketing Agent...")
    marketing = marketing_agent(sentiment)

    print("[STEP] Running Risk Agent...")
    risks_from_agent = risk_agent(data)

    print("[STEP] Running Finance Agent...")
    finance = finance_agent(metrics)

    print("[STEP] Running Critic Agent...")
    critic = critic_agent(data)

    print("[STEP] Running PM Agent...")
    decision = pm_agent(data, sentiment, finance)

    # ---------------------------
    # 2. Dynamic Metric Impact
    # ---------------------------
    metrics_impact = {}

    if "dau" in metrics:
        metrics_impact["dau"] = get_metric_drop(metrics["dau"])

    if "retention_d7" in metrics:
        metrics_impact["retention_d7"] = get_metric_drop(metrics["retention_d7"])

    if "conversion" in metrics:
        metrics_impact["conversion"] = get_metric_drop(metrics["conversion"])

    # ---------------------------
    # 3. Dynamic Summary
    # ---------------------------
    summary = (
        "Key product metrics show declining trends and user sentiment is negative, "
        "indicating degraded user experience after the new feature rollout."
    )

    # ---------------------------
    # 4. Dynamic Risk Register
    # ---------------------------
    risk_register = []

    # From data issues
    if "dau" in data["issues"]:
        risk_register.append({
            "risk": "User engagement drop",
            "mitigation": "Improve feature stability and usability"
        })

    if "retention_d7" in data["issues"]:
        risk_register.append({
            "risk": "Poor user retention",
            "mitigation": "Fix onboarding and usability issues"
        })

    if "conversion" in data["issues"]:
        risk_register.append({
            "risk": "Revenue loss",
            "mitigation": "Fix checkout/payment flow issues"
        })

    if "crash_rate" in data["issues"]:
        risk_register.append({
            "risk": "High crash rate",
            "mitigation": "Deploy hotfix for stability"
        })

    # From sentiment
    if sentiment["overall"] == "negative":
        risk_register.append({
            "risk": "Negative brand perception",
            "mitigation": "Communicate transparently with users"
        })

    # Include risk_agent outputs (if any)
    for r in risks_from_agent:
        risk_register.append({
            "risk": r[0],
            "mitigation": r[1]
        })

    # ---------------------------
    # 5. Action Plan (24–48 hrs)
    # ---------------------------
    action_plan = [
        {"owner": "Engineering", "action": "Fix critical bugs (within 24 hrs)"},
        {"owner": "Backend", "action": "Reduce API latency (within 48 hrs)"},
        {"owner": "QA", "action": "Run full regression test suite"},
        {"owner": "Product", "action": "Re-evaluate rollout criteria"}
    ]

    # ---------------------------
    # 6. Communication Plan
    # ---------------------------
    communication_plan = {
    "internal": marketing.get("internal", "Notify stakeholders"),
    "external": marketing.get("external", "Update users"),
    "note": "Generated by Marketing Agent based on sentiment analysis"
    }

    # ---------------------------
    # 7. Confidence Score (Dynamic)
    # ---------------------------
    issue_count = len(data["issues"])
    confidence = round(max(0.3, 1 - (issue_count * 0.1)), 2)

    # ---------------------------
    # 8. Final Output
    # ---------------------------
    final = {
        "decision": decision,

        "rationale": {
            "summary": summary,
            "metrics_impact": metrics_impact,
            "sentiment_summary": sentiment
        },

        "risk_register": risk_register,

        "action_plan": action_plan,

        "communication_plan": communication_plan,

        "confidence_score": confidence,

        "confidence_improvement": [
            "Stabilized metrics over next few days",
            "Crash rate reduced below threshold",
            "Improved user sentiment after fixes"
        ],

        "critic_notes": critic
    }

    print("===== WAR ROOM END =====")

    return final